title : " TACHEGOUM TOUYEM JUNIOR " 
logo :  img/nny.jpg
description : "PORTFOLIO  Administrateur Systèmes & Réseaux • Technicien Informatique • Sécurité & Automatisme" 
show_downloads : true 
thème:  jekyll-theme-minimal
lang : fr
